#!/bin/sh
# Project-OS session opener — reference implementation of BEHAVIOR.md Part 1's
# self-injecting protocol clause, running on the repo that authors it.
#
# NOT REGISTERED. Wiring a SessionStart hook changes how every future session in
# this repo behaves, which is Leo's call, not an agent's. To enable, add to
# .claude/settings.json:
#   { "hooks": { "SessionStart": [ { "hooks": [ { "type": "command",
#       "command": ".claude/hooks/project-os-open.sh" } ] } ] } }
#
# Why it exists: a protocol that must be remembered is a protocol that lapses.
# Measured elsewhere in the portfolio, 4 of 10 sessions delivered work having
# never opened the skill while the closing gate stayed healthy — the two halves
# fail differently, and only measurement shows which.
#
# THE TRAP THIS GUARDS AGAINST: if the status artifact is missing, this exits 0
# and injects nothing — the install looks done and does nothing. Installation is
# complete only when an injection has been OBSERVED in a real session with a
# deliberately reddened row.

ROOT="$(git rev-parse --show-toplevel 2>/dev/null)" || ROOT="."
STATUS="$ROOT/docs/project-os-status.md"

if [ ! -f "$STATUS" ]; then
  # Loud, not silent: the absence is itself the finding.
  echo "[Project-OS] status artifact missing at docs/project-os-status.md — run: node scripts/freshness.mjs"
  exit 0
fi

RED="$(sed -n '/^## RED/,$p' "$STATUS" | sed -n '3,12p')"

echo "[Project-OS] Session protocol, injected automatically (nothing to invoke to receive this)."
echo ""
echo "Opening: docs/project-os-status.md is generated by scripts/freshness.mjs and is the one"
echo "place that says what the protocol is owed right now. Read it instead of re-deriving."
echo ""
echo "Closing, before you commit: the three spec files move in lockstep; a shipped version needs"
echo "a CHANGELOG entry with idempotent migration steps; a new Part 2 artifact must be classified"
echo "in project-os-manifest.json. If a gate is red, write the missing artifact — never narrow the"
echo "check. Never push without Leo saying so."

if [ -n "$RED" ]; then
  echo ""
  echo "OWED NOW:"
  echo "$RED"
fi
